#!/bin/sh /etc/rc.common
# jodu5164x-updater
# Runs jodu5164x-telnet-updater.sh as a supervised background service so
# the main dashboard never blocks on telnet.

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/jodu5164x-telnet-updater.sh
	procd_set_param respawn
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}
